name: Build Wheels

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: build-env
          use-only-tar-bz2: true

      - name: Install dependencies
        run: |
          conda install -y setuptools 
          conda install -y pytorch pytorch-cuda=12.1 -c pytorch -c nvidia
          conda install -y nvidia::cuda-toolkit=12.1

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels
        run: |
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PLATFORM: manylinux2014_x86_64
          CIBW_ENVIRONMENT: CUDA_HOME=/usr/local/cuda-12.1

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse/
